include: package:sizzle_lints/lints.yaml

analyzer:
  errors:
    eol_at_end_of_file: ignore
    directives_ordering: ignore
  exclude: 
    - "lib/src/core/localization/generated/**"

dart_code_metrics:
  extends:
    - package:sizzle_lints/dcm.yaml